#----------------------------------------------------------------
# Travis CI for R Packages
# https://docs.travis-ci.com/user/languages/r
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran

matrix:
  include:
    - os: linux
      r: release

notifications:
  email:
    on_success: change
    on_failure: change
